# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Savidu Karunaratne
email: saviduhk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Savidu Karunaratne's portfolio and blog
twitter_username: username
github_username: saviduhk
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Added Collections for portfolio
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/


include:
  - _pages
  - _portfolio

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Savidu Karunaratne"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "A 3D Generlist interested in procedural workflows for game creation!"
  links:
    - label: "Latest Showreel"
      icon: "fas fa-fw fa-link"
      url: "https://vimeo.com/828943674"
    - label: "Resume"
      icon: "fab fa-fw fa-file"
      url: "/assets/cv_savidu.pdf"
    - label: "saviduhk@gmail.com"
      icon: "fab fa-fw fa-file"
    - label: "Art Station"
      icon: "fas fa-fw fa-link"
      url: "https://www.artstation.com/saviduhk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saviduhk"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/saviduhk/"

footer:
  links:
    - label: "Resume"
      icon: "fa-solid fa-file"
      url: "/assets/cv_savidu.pdf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saviduhk"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/saviduhk/"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
   
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
